export enum WOFPadWords {
    READY = "ready",
    FIRST = "first",
    NO = "no",
    BLANK = "blank",
    NOTHING = "nothing",
    YES = "yes",
    WHAT = "what",
    UHHH = "uhhh",
    LEFT = "left",
    RIGHT = "right",
    MIDDLE = "middle",
    OKAY = "okay",
    WAIT = "wait",
    PRESS = "press",
    YOU = "you",
    YOU_ARE = "you are",
    YOUR = "your",
    YOURE = "you're",
    UR = "ur",
    U = "u",
    UH_HUH = "uh huh",
    UH_UH = "uh uh",
    WHATQ = "what",
    DONE = "done",
    NEXT = "next",
    HOLD = "hold",
    SURE = "sure",
    LIKE = "like"
}

export enum WOFDisplayWords {
    YES = "yes",
    FIRST = "first",
    DISPLAY = "display",
    OKAY = "okay",
    SAYS = "says",
    NOTHING = "nothing",
    _EMPTY = "",
    BLANK = "blank",
    NO = "no",
    LED = "led",
    LEAD = "lead",
    READ = "read",
    RED = "red",
    REED = "reed",
    LEED = "leed",
    HOLD_ON = "hold on",
    YOU = "you",
    YOU_ARE = "you are",
    YOUR = "your",
    YOURE = "you're",
    UR = "ur",
    THERE = "there",
    THEYRE = "they're",
    THEIR = "their",
    THEY_ARE = "they are",
    SEE = "see",
    C = "c",
    CEE = "cee",
}

export enum WOFPosition {
    TOP_LEFT = "TOP_LEFT",
    TOP_RIGHT = "TOP_RIGHT",
    MIDDLE_LEFT = "MIDDLE_LEFT",
    MIDDLE_RIGHT = "MIDDLE_RIGHT",
    BOTTOM_LEFT = "BOTTOM_LEFT",
    BOTTOM_RIGHT = "BOTTOM_RIGHT"
}